### ISSUE TITLE
SST user - plugin line deletes the password

### ISSUE THREAD

**Issue by eRadical** [mrlesmithjr/ansible-mariadb-galera-cluster#110]
https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/blob/9b188d60cb14eda421769d66e59c792919b2227d/defaults/main.yml#L163-L171

In the above because of the line:
```
plugin: "unix_socket"
```
the password is removed and the grant looks like:
```
GRANT RELOAD, PROCESS, LOCK TABLES, BINLOG MONITOR ON *.* TO `mariadb-sst`@`localhost` IDENTIFIED VIA unix_socket;
```
and the SST freezes.

If I remove the line the grant will look like:
```
GRANT RELOAD, PROCESS, LOCK TABLES, BINLOG MONITOR ON *.* TO `mariadb-sst`@`localhost` IDENTIFIED BY PASSWORD '*13D253680F898B77D9661FACDE29E71EA9A96DFF';
```
and all works well.

Is it ok to change the lines to:
```
#mariadb_auth_plugin: "unix_socket"
mariadb_sst_user:
  - name: "{{ mariadb_sst_username }}"
    hosts:
      - "localhost"
    plugin: "{{ mariadb_auth_plugin | default(omit) }}"
    password: "{{ mariadb_sst_password }}"
    priv: "*.*:RELOAD,PROCESS,LOCK TABLES,BINLOG MONITOR"
```

The problem is that the user must exist as a system user to work ok, otherwise it will not work w/ `unix_socket` and you need a passwod.

Thoughts?
