### ISSUE TITLE
Users with table permissions fail to create

### ISSUE THREAD

**Issue by 32bitbradley** [mrlesmithjr/ansible-mariadb-galera-cluster#122]
**Describe the bug**
When trying to create users with permissions over specific tables, the user creation task fails as the table hasn't yet been created.

In my testing, moving the user creation task to after the database creation task in `main.yml` fixes these issues.

**To Reproduce**
Steps to reproduce the behaviour:
1. Get the playbook to create a user with table specific permissions IE

```yaml
  - name: api
    hosts:
      - "%"
      - "127.0.0.1"
      - "::1"
      - "localhost"
    password: "{{ api_password }}"
    encrypted: no
    priv:
      "users.logins": "SELECT,INSERT,UPDATE,DELETE"

```

**Expected behavior**

The users and new tables should be created.

**Desktop (please complete the following information):**
 - Ansible controller OS: Linux Mint 20.2 
 - Ansible Host OS: Centos 7
