### ISSUE TITLE
Need to add delay between "setup_cluster | restarting node to apply config changes (other nodes)"

### ISSUE THREAD

**Issue by roumano** [mrlesmithjr/ansible-mariadb-galera-cluster#128]
**Is your feature request related to a problem? Please describe.**
When a configuration change on our Galera Cluster, the ansible tasks `setup_cluster | restarting node to apply config changes (other nodes)` happen too quickly between other nodes so the cluster is not in a good state for dozen a second.

as example, the restart happen at 5h28m14 for the second node and at 5h28m24s for the third node.
**10 seconds** between them it's too short in our case as the second node it's not yet Synced in the Galera cluster

The `throttle :1` is working as expected but need to add a wait for X second (or even better wait for server integrate to the cluster pool + wait for X second)

**Describe the solution you'd like**
i'm thinking to move this specific tasks on a include tasks and add a wait_for delay on it

What it's you point of view ?

**Comment by roumano** [comment]
I have replace this code :  
```
 - name: setup_cluster | restarting node to apply config changes (other nodes)
   service: # noqa 503
     name: "{{ mariadb_systemd_service_name }}"
     state: "restarted"
   become: true
   throttle: 1
   when: >
     galera_cluster_configured.stat.exists and
     _mariadb_galera_cluster_reconfigured.changed and
     inventory_hostname != galera_mysql_first_node
```

With :  
```
- name: Per server, wait and restarting node
  include_tasks: restart_node.yml
  with_items: "{{ ansible_play_hosts }}"
  when:
  - inventory_hostname == item
  - galera_cluster_configured.stat.exists
  - _mariadb_galera_cluster_reconfigured.changed
  - inventory_hostname != galera_mysql_first_node
```

And the new file restart_node.yml :  
```
---
- name: Sleep for 60 seconds and timeout
  wait_for:
    delay: 60
    timeout: 0
  check_mode: no

- name: setup_cluster | restarting node to apply config changes (other nodes)
  service: # noqa 503
    name: "{{ mariadb_systemd_service_name }}"
    state: "restarted"
  become: true
```

and it's working as expected
ps : the check_mode: no is only used for testing with `ansible-playbook --check --diff`
ps2: it's possible to add a variable for the delay, like `delay: "{{ galera_delay_between_restart | default ('60') }}"`
