### ISSUE TITLE
github actions broken

### ISSUE THREAD

**Issue by FrancYescO** [mrlesmithjr/ansible-mariadb-galera-cluster#187]
Seems the autodeploy via GH actions is broken (maybe GALAXY_API_KEY expired/invalid) and ansible-galaxy is still "freezed" to the old version:

https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/actions/runs/7473232146/job/20337004636

**Comment by eRadical** [comment]
Need help from @mrlesmithjr on this one.
But meanwhile you can get the role directly from Github via https:

```
roles:
  - name: your_folder_name
    src: https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster.git
    scm: git
```
