### ISSUE TITLE
galera.cnf fail mandatory variable 'ansible_[interface]' not defined

### ISSUE THREAD

**Issue by thesefer** [mrlesmithjr/ansible-mariadb-galera-cluster#243]
**Describe the bug**
This time I think I hit a bug I am not able to resolve on my own.

error
```
TASK [mrlesmithjr.mariadb-galera-cluster : setup_cluster | configuring settings for mariadb and galera src={{ file.name }}.j2, dest=/{{ file.name }}, mode={{ file.mode |default ('0644') }}, follow=True] ***************************************************************************************************************
ok: [srv02] => (item={'name': 'etc/mysql/debian.cnf'})
ok: [srv01] => (item={'name': 'etc/mysql/debian.cnf'})
ok: [srv02] => (item={'name': 'etc/mysql/my.cnf'})
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleFilterError: Mandatory variable 'ansible_ens192'  not defined.
failed: [srv02] (item={'name': 'etc/mysql/conf.d/galera.cnf'}) => {"ansible_loop_var": "file", "changed": false, "file": {"name": "etc/mysql/conf.d/galera.cnf"}, "msg": "AnsibleFilterError: Mandatory variable 'ansible_ens192'  not defined."}
ok: [srv01] => (item={'name': 'etc/mysql/my.cnf'})
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleFilterError: Mandatory variable 'ansible_eno1'  not defined.
failed: [srv01] (item={'name': 'etc/mysql/conf.d/galera.cnf'}) => {"ansible_loop_var": "file", "changed": false, "file": {"name": "etc/mysql/conf.d/galera.cnf"}, "msg": "AnsibleFilterError: Mandatory variable 'ansible_eno1'  not defined."}
```

vars
```
mariadb_version: "10.6.18"
galera_enable_mariadb_repo: false
mariadb_bind_address: 127.0.0.1
galera_cluster_bind_interface: "{{ ansible_default_ipv4['interface'] }}"
galera_cluster_name: "icinga-db-cluster"
galera_cluster_nodes_group: "icinga-cluster"
galera_mysql_first_node: "{{ groups[galera_cluster_nodes_group][0] }}"
mariadb_charset_server: utf8mb4
mariadb_collation_server: "utf8mb4_unicode_ci"
mariadb_charset_client: utf8mb4
mariadb_databases:
  - name: icingadb
  - name: icingaweb
  - name: vspheredb
  - name: "{{ icingaweb2_resources['director_db']['dbname'] }}"
mariadb_mysql_users:
  - name: icingaweb
    hosts:
      - "%"
    password: "{{ icingaweb2_db['password'] }}"
    priv: "icingaweb.*:ALL"
  - name: icingadb
    hosts:
      - "%"
    password: "{{ icingadb_database_password }}"
    priv: "icingadb.*:ALL"
  - name: vspheredb
    hosts:
      - "%"
    password: "onepassword"
    priv: "vspheredb.*:ALL"
  - name: "{{ icingaweb2_resources['director_db']['username'] }}"
    hosts:
      - "%"
    password: "{{ icingaweb2_resources['director_db']['password'] }}"
    priv: "{{ icingaweb2_resources['director_db']['dbname'] }}.*:ALL"
mariadb_mysql_root_password: "superstrongpassword"
```

debug output:
```
TASK [mrlesmithjr.mariadb-galera-cluster : Debug msg={{ galera_cluster_bind_interface }}] ***
ok: [srv01] => {
    "msg": "eno1"
}
ok: [srv02] => {
    "msg": "ens192"
}

TASK [mrlesmithjr.mariadb-galera-cluster : Debug msg={{ galera_cluster_bind_address }}] ***
ok: [srv01] => {
    "msg": "10.10.10.1"
}
ok: [srv02] => {
    "msg": "10.10.10.2"
}

ok: [srv02] => {
    "msg": {
[...]
        "srv01": {
[...]
            "ansible_eno1": {
                "active": true,
                "device": "eno1",
                "ipv4": {
                    "address": "10.10.10.1",
[...]
        "srv02": {
[...]
            "ansible_ens192": {
                "active": true,
                "device": "ens192",
[...]
               "ipv4": {
                    "address": "10.10.10.2",

same for srv01
```

**To Reproduce**
1. Commit https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/commit/f44a952b4fdbf8a142d0d66431b4c46a37cba14a
2. Add debug tasks in `setup_cluster.yml`
3. Run role

Debug tasks:
```
- name: Debug
  ansible.builtin.debug:
    msg: "{{ galera_cluster_bind_interface }}"

- name: Debug
  ansible.builtin.debug:
    msg: "{{ galera_cluster_bind_address }}"

- name: Debug
  ansible.builtin.debug:
    msg: "{{ hostvars }}"
```

**Expected behavior**
The variables and values are defined and assigned as per above. It still seems to fail at https://github.com/mrlesmithjr/ansible-mariadb-galera-cluster/blob/master/templates/etc/mysql/conf.d/galera.cnf.j2#L51

**Comment by thesefer** [comment]
I defined the following variable in my group vars because it seems the default vars weren't read properly and it results in the following within the galera.cnf

group_vars
```
galera_cluster_bind_address: "{{ hostvars[inventory_hostname]['ansible_' + galera_cluster_bind_interface]['ipv4']['address'] }}"
```

galera.cnf
```
wsrep_cluster_address="gcomm://{{ hostvars[inventory_hostname]['ansible_' + galera_cluster_bind_interface]['ipv4']['address'] }},{{ hostvars[inventory_hostname]['ansible_' + galera_cluster_bind_interface]['ipv4']['address'] }}"
```

**Comment by thesefer** [comment]
This is driving me crazy. If I use 2 vms this runs through as per my initial config (tho in my previous comment the variable expansion still does not work, so `galera_cluster_bind_address` is useless.

But if I use a physical machine and a vm, I cannot get past the `galera.cnf`.

I just added the following debug tasks, proving it should work:
```
- name: Debug Nodes
  ansible.builtin.debug:
    msg: "{{ galera_cluster_nodes }}"

- name: Debug bind_address
  ansible.builtin.debug:
    msg: "{{ hostvars[inventory_hostname]['ansible_' ~ galera_cluster_bind_interface]['ipv4']['address'] }}"
```

Note that I changed from `node` to `inventory_hostname` in this context. The ip's match the machines!
Output:
```
TASK [mrlesmithjr.mariadb-galera-cluster : Debug Nodes msg={{ galera_cluster_nodes }}] ***********************************************************************************************************************************************************************************************************************************
ok: [hw-srv01] => {
    "msg": [
        "hw-srv01",
        "vm-srv02"
    ]
}
ok: [vm-srv02] => {
    "msg": [
        "hw-srv01",
        "vm-srv02"
    ]
}

TASK [mrlesmithjr.mariadb-galera-cluster : Debug bind_address msg={{ hostvars[inventory_hostname]['ansible_' ~ galera_cluster_bind_interface]['ipv4']['address'] }}] *****************************************************************************************************************************************************
ok: [hw-srv01] => {
    "msg": "10.10.10.1"
}
ok: [vm-srv02] => {
    "msg": "10.10.10.2"
}
```

But suddenly this information is lost?
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleFilterError: Mandatory variable 'ansible_ens192'  not defined.
failed: [vm-srv02] (item={'name': 'etc/mysql/conf.d/galera.cnf'}) => {"ansible_loop_var": "file", "changed": false, "file": {"name": "etc/mysql/conf.d/galera.cnf"}, "msg": "AnsibleFilterError: Mandatory variable 'ansible_ens192'  not defined."}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.errors.AnsibleFilterError: Mandatory variable 'ansible_eno1'  not defined.
failed: [hw-srv01] (item={'name': 'etc/mysql/conf.d/galera.cnf'}) => {"ansible_loop_var": "file", "changed": false, "file": {"name": "etc/mysql/conf.d/galera.cnf"}, "msg": "AnsibleFilterError: Mandatory variable 'ansible_eno1'  not defined."}
```
