### ISSUE TITLE
Feature request: Allow arbitrary additions to wsrep_provider_options

### ISSUE THREAD

**Issue by techdaddies-kevin** [mrlesmithjr/ansible-mariadb-galera-cluster#9]
Simply put - I need to configure auto eviction in our cluster, but as far as I can tell, it isn't possible to do this within this role. Because of the huge amount of options that can be added to wsrep_provider_options, I think it would be great to modify this role so that I, as an end user, can define 'extra_wsrep_provider_options' that are then tacked on to the end of the wsrep_provider_options line in the galera configuration file. For example:

```
extra_wsrep_provider_options:
  evs.auto_evict: 1
  evs.delayed_margin: 'PT5S'
  evs.delayed_keep_period: 'PT45S'
```

The above would append the end of the wsrep_provider_options line like follows:

wsrep_provider_options = "....auto generated options; evs.auto_evict = 1; evs.delayed_margin = PT5S; evs.delayed_keep_period = PT45S"

By adopting a structure similar to this, it would allow us to very tightly control the configuration of Galera without needing the individual options to be added to this role first.

**Comment by mrlesmithjr** [comment]
@techdaddies-kevin Thanks for the idea. I have played around a bit with this and it looks like the way it will need to be done would be as below.

Define the vars:
```
extra_wsrep_provider_options:
  evs.auto_evict: 1
  evs.delayed_margin: 'PT5S'
  evs.delayed_keep_period: 'PT45S'
```
Then a bit of Jinja2:
```
{% if extra_wsrep_provider_options is defined %}
wsrep_provider_options = "{% for item in extra_wsrep_provider_options %}{% set _key = item.split(': ')[0] %}{% set _val = extra_wsrep_provider_options[_key] %}{{ _key }} = {{ _val }}{% if not loop.last %}, {% endif %}{% endfor %}"
{% endif %}
```
Results in:
```
wsrep_provider_options = "evs.auto_evict = 1, evs.delayed_keep_period = PT45S, evs.delayed_margin = PT5S"
```
