### ISSUE TITLE
Adding users through mariadb_mysql_users variable fails because mariadb isn't running yet

### ISSUE THREAD

**Issue by margana** [mrlesmithjr/ansible-mariadb-galera-cluster#97]
Hello,

I'm using this role to install on CentOS 8 stream and it works pretty well, thanks :smile: 

The problem arises when I set `mariadb_mysql_users` and do a clean install.

For example:
```
mariadb_mysql_users:
  - name: test
    password: test
    hosts:
      - "%"
```

The mysql_users task fails and complains about not being able to connect to the server. When I check the server I notice that the mariadb daemon is indeed not running yet.

If I run the playbook once before setting the variable then the user is added just fine.

What am I missing here?

Thanks in advance.
